name: nfe_decoder
description: A library that decodes NFe from the URL of the QRCode.
version: 0.1.3
repository: https://github.com/mrhaubrich/nfe_decoder

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.25.2
