name: nfe_decoder

description: A library that decodes NFe from the URL of the QRCode.

version: 0.2.0

repository: https://github.com/mrhaubrich/nfe_decoder

environment:
  sdk: ">=3.10.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  html: ^0.15.6
  http: ^1.6.0

dev_dependencies:
  lints: ^6.1.0
  saropa_lints: ^13.11.1
  test: ^1.31.1
